kernel:
  image: pwfoo/os-alpine-kernel:latest
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"

init:
  - pwfoo/init-busybox:latest
  # default packages from kernel.tar missing?!
  - pwfoo/os-alpine-modules:latest
  - pwfoo/init-ca-certificates:latest
  - pwfoo/init-crun:latest
  - pwfoo/init-rustysd:latest

#onboot:

        
services:
  - name: rngd
    image: pwfoo/rngd:latest
    capabilities:
     - all
    binds:
     - /lib/modules:/lib/modules

  - name: mdevd
    image: pwfoo/os-mdevd:latest
    capabilities:
    - all
    binds:
    - /lib/modules:/lib/modules
    - /lib/firmware:/lib/firmware

  - name: udhcpc
    image: pwfoo/udhcpc:latest
    net: host
    binds:
    - /etc/resolv.conf:/etc/resolv.conf    
    capabilities:
    - CAP_NET_ADMIN
    - CAP_NET_RAW
    - CAP_SYS_ADMIN

  - name: sshd
    image: pwfoo/sshd:latest
    net: host
    pid: host
    capabilities:
    - all
    binds:
    - /:/host

#  - name: docker
#    image: docker:stable-dind
#    capabilities:
#     - all
#    net: host
#    binds:
#     - /run/docker/cgroup:/sys/fs/cgroup
#     - /etc/resolv.conf:/etc/resolv.conf
#     - /var/lib/docker:/var/lib/docker
#     - /lib/modules:/lib/modules
#     - /etc/docker/daemon.json:/etc/docker/daemon.json
#    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]

#  - name: podman
#    image: mgoltzsche/podman:latest
#    capabilities: 
#     - all
#    net: host
#    mounts:
#     - type: cgroup
#       options: ["rw","nosuid","noexec","nodev","relatime"]
#    binds:
#     - /etc/resolv.conf:/etc/resolv.conf
#     - /var/lib/containers:/var/lib/containers
#     - /lib/modules:/lib/modules

files:
#  - path: /var/lib/containers
#    directory: true
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
